---
title: "Untitled"
output: 
  html_document: 
    keep_md: yes
date: "2023-02-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
```

```{r}
getwd()
```


Simulated malaria data
```{r}
malaria <- read_csv("data/malaria.csv") %>% clean_names()
```

```{r}
names(malaria)
```

```{r}
head(malaria)
```
not tidy because column names contain data-'rdt' is followed by the organisms' age class

make the data tidy through Pivot longer
```{r}
malaria_long <- malaria %>% 
  pivot_longer(cols=starts_with("malaria_rdt"),
               names_to = "age_class",
               values_to = "cases") %>% 
  select(newid, data_date, submitted_date, location_name, province, district, age_class, cases)
```

should also get rid of 'malaria_rdt' in each age class and just show the numbers to make even more tidy

Which district had the highest number of cases on July 30, 2020?
```{r}
malaria_long %>% 
  filter(data_date=="2020-07-30") %>% 
  group_by(district) %>% 
  summarize(tot_cases=sum(cases, na.rm=T)) %>% 
  arrange(-tot_cases) #other way of doing descending order
```
Bolo district had the highest number of cases on July 30, 2020
