---
title: "lab_6_warmup"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. load the libraries 'tidyverse' and 'janitor' 
```{r}
library(tidyverse)
library(janitor)
```
##2. load the 'bison.csv' data

```{r}
bison <- read.csv("Data/bison.csv")
```


## 2. What are the dimensions and structure of the data?

```{r}
dim(bison)
```

```{r}
glimpse(bison)
```
```{r}
summarise(bison)
```

## 3. We are only interested in code, sex, weight, year of birth. Restrict the data to these variables and store the dataframe as a new object.

```{r}
names(bison)
```


```{r}
bison_new <- bison %>% 
  select("animal_code", "animal_sex", "animal_weight", "animal_yob")
```

## 4. Pull out all the animals born between the years 1980-1990

```{r}
bison_new %>% 
  filter(between(animal_yob, 1980, 1990))

```
or can do:
```{r}
bison_new %>% 
  filter(animal_yob>=1980 & animal_yob<=1990)
```

## How many males and females?

```{r}
males <- bison_new %>% #firt pull out the males
  filter(between(animal_yob, 1980, 1990)) %>% 
  filter(animal_sex=="M")
males
#or
table(males$animal_sex)
```

```{r}
females <- bison_new %>% #firt pull out the females
  filter(between(animal_yob, 1980, 1990)) %>% 
  filter(animal_sex=="F")
females
#or
table(females$animal_sex)
```
## mean of males
```{r}
mean(males$animal_weight)
```


## mean of females
```{r}
mean(females$animal_weight)
```


